### ISSUE TITLE
fix exeception when ActionEntryPoints are clicked 

### ISSUE THREAD

**Issue by almibe** [almibe/library-weasel-dash-panel#8]
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at com.sun.javafx.collections.ObservableSetWrapper$1.next(ObservableSetWrapper.java:219)
	at org.libraryweasel.app.admin.dash.StartDash$updateDisplay$1.run(StartDash.kt:105)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by almibe** [comment]
Nevermind these aren't related.
